# Pandas CSV reader & basic analysis
## Employee Dataset

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("Employee.csv")
df

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
...,...,...,...,...,...,...,...,...,...
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [5]:
df.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1

In [6]:
df.tail()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [7]:
df.dtypes

Education                      str
JoiningYear                  int64
City                           str
PaymentTier                  int64
Age                          int64
Gender                         str
EverBenched                    str
ExperienceInCurrentDomain    int64
LeaveOrNot                   int64
dtype: object

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4653 entries, 0 to 4652
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Education                  4653 non-null   str
 1   JoiningYear                4653 non-null   int64
 2   City                       4653 non-null   str
 3   PaymentTier                4653 non-null   int64
 4   Age                        4653 non-null   int64
 5   Gender                     4653 non-null   str
 6   EverBenched                4653 non-null   str
 7   ExperienceInCurrentDomain  4653 non-null   int64
 8   LeaveOrNot                 4653 non-null   int64
dtypes: int64(5), str(4)
memory usage: 327.3 KB

In [11]:
df.mean(numeric_only=True)

JoiningYear                  2015.062970
PaymentTier                     2.698259
Age                            29.393295
ExperienceInCurrentDomain       2.905652
LeaveOrNot                      0.343864
dtype: float64

In [12]:
df.median(numeric_only=True)

JoiningYear                  2015.0
PaymentTier                     3.0
Age                            28.0
ExperienceInCurrentDomain       3.0
LeaveOrNot                      0.0
dtype: float64

In [13]:
df.min(numeric_only=True)

JoiningYear                  2012
PaymentTier                     1
Age                            22
ExperienceInCurrentDomain       0
LeaveOrNot                      0
dtype: int64

In [14]:
df.max(numeric_only=True)

JoiningYear                  2018
PaymentTier                     3
Age                            41
ExperienceInCurrentDomain       7
LeaveOrNot                      1
dtype: int64

In [15]:
df.count()

Education                    4653
JoiningYear                  4653
City                         4653
PaymentTier                  4653
Age                          4653
Gender                       4653
EverBenched                  4653
ExperienceInCurrentDomain    4653
LeaveOrNot                   4653
dtype: int64

In [16]:
df.describe()

,JoiningYear,PaymentTier,Age,ExperienceInCurrentDomain,LeaveOrNot
count,4653.000000,4653.000000,4653.000000,4653.000000,4653.000000
mean,2015.062970,2.698259,29.393295,2.905652,0.343864
std,1.863377,0.561435,4.826087,1.558240,0.475047
min,2012.000000,1.000000,22.000000,0.000000,0.000000
25%,2013.000000,3.000000,26.000000,2.000000,0.000000
50%,2015.000000,3.000000,28.000000,3.000000,0.000000
75%,2017.000000,3.000000,32.000000,4.000000,1.000000
max,2018.000000,3.000000,41.000000,7.000000,1.000000

In [19]:
df[(df["Age"] > 30) & (df["City"] == "Pune")]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
11,Bachelors,2016,Pune,3,34,Male,No,3,0
12,Bachelors,2018,Pune,3,32,Male,Yes,5,1
17,Bachelors,2014,Pune,3,34,Male,No,4,0
28,Bachelors,2013,Pune,2,31,Female,No,2,1
34,Bachelors,2017,Pune,2,37,Female,No,0,1
...,...,...,...,...,...,...,...,...,...
4620,Bachelors,2015,Pune,2,38,Female,No,4,1
4625,Bachelors,2013,Pune,3,37,Male,No,3,0
4644,Bachelors,2015,Pune,3,32,Female,Yes,1,1
4645,Masters,2017,Pune,2,31,Female,No,2,0
4649,Masters,2013,Pune,2,37,Male,No,2,1

In [20]:
df[["Education", "Age", "City"]]

      Education  Age       City
0     Bachelors   34  Bangalore
1     Bachelors   28       Pune
2     Bachelors   38  New Delhi
3       Masters   27  Bangalore
4       Masters   24       Pune
...         ...  ...        ...
4648  Bachelors   26  Bangalore
4649    Masters   37       Pune
4650    Masters   27  New Delhi
4651  Bachelors   30  Bangalore
4652  Bachelors   33  Bangalore

[4653 rows x 3 columns]

In [21]:
df.iloc[:10]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
5,Bachelors,2016,Bangalore,3,22,Male,No,0,0
6,Bachelors,2015,New Delhi,3,38,Male,No,0,0
7,Bachelors,2016,Bangalore,3,34,Female,No,2,1
8,Bachelors,2016,Pune,3,23,Male,No,1,0
9,Masters,2017,New Delhi,2,37,Male,No,2,0

In [22]:
df.iloc[-10:]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
4643,Bachelors,2013,Bangalore,3,31,Female,No,5,0
4644,Bachelors,2015,Pune,3,32,Female,Yes,1,1
4645,Masters,2017,Pune,2,31,Female,No,2,0
4646,Bachelors,2013,Bangalore,3,25,Female,No,3,0
4647,Bachelors,2016,Pune,3,30,Male,No,2,0
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [25]:
filtered_df = df[df["Age"] > 30]
filtered_df.to_csv("filtered_employee.csv", index=False)